version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: unless-stopped
    ports:
      - "5050:5050"
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=UTC
    volumes:
      - pearl_logs:/app/pearl_log.txt
      - royalty_logs:/app/royalty/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5050/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:5050
      - TZ=UTC
    depends_on:
      backend:
        condition: service_healthy

volumes:
  pearl_logs:
  royalty_logs:

# Run in production with: docker compose -f docker-compose.yml up -d
